version: '3'

services:
  build:
    build: .
    command: make master.pdf
    working_dir: /main
    volumes:
      - './:/main'
  shell:
    image: build
    command: bash
    working_dir: /main
    volumes:
      - './:/main'
